# Generated by Django 4.2.1 on 2024-07-12 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=6, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('roll_no', models.CharField(max_length=50, unique=True)),
                ('student_class', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(max_length=255)),
                ('mothers_name', models.CharField(max_length=255)),
                ('parents_phone_number', models.CharField(max_length=15)),
                ('student_phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('interests', models.TextField()),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='students/students_profile_imges/')),
                ('current_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='students.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_history', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('outcome', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/achievement_photos/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
            },
        ),
    ]
