# Generated by Django 4.2.1 on 2024-07-12 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.school')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.batch')),
                ('subjects', models.ManyToManyField(to='teachers.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ia1_marks', models.IntegerField(blank=True, default=None, null=True)),
                ('ia2_marks', models.IntegerField(blank=True, default=None, null=True)),
                ('ia3_marks', models.IntegerField(blank=True, default=None, null=True)),
                ('midterm_marks', models.IntegerField(blank=True, default=None, null=True)),
                ('final_marks', models.IntegerField(blank=True, default=None, null=True)),
                ('total', models.IntegerField(blank=True, default=None, editable=False, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.enrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.subject')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subject_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.subjectgroup'),
        ),
    ]
